### ISSUE TITLE
run_demo.py : IndexError: index out of range in self

### ISSUE THREAD

**Issue by Jenny-Jo** [princeton-nlp/DensePhrases#31]
Hi, 
I'm trying to utilize DensePhrases as Korean version, not English version. The trained model is bert-base-multilingual-cased model (not span-bert model because it doesn't support Korean) on korquad dataset. The dataset sourced from Korean Wikipedia was manually preprocessed and used to create a custom phrase index.

The error that I encountered when running run_demo.py is as shown below:
```

02/14/2023 07:08:04 - ERROR - tornado.access -   500 POST /query2vec_api (127.0.0.1) 11.09ms
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---feature : {'input_ids': [101, 48556, 16617, 119202, 9323, 51431, 14040, 34907, 10892, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'qas_id': 0, 'question_text': '한국전쟁 발발시점은'} , 
 example['question_text'] : 한국전쟁 발발시점은
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---query_eval_features [{'input_ids': [101, 48556, 16617, 119202, 9323, 51431, 14040, 34907, 10892, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'qas_id': 0, 'question_text': '한국전쟁 발발시점은', 'unique_id': 1000000000}]---
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---question_dataloader <torch.utils.data.dataloader.DataLoader object at 0x7f76d1e7da60>---
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---DEVICE cpu---
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---BATCH [tensor([[   101,  48556,  16617, 119202,   9323,  51431,  14040,  34907,  10892,
            102,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0]]), tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), tensor([0])]---
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   ---len(batch) 4---
02/14/2023 07:08:04 - INFO - densephrases.utils.embed_utils -   --tmp 1---
02/14/2023 07:08:04 - ERROR - run_demo -   Exception on /query2vec_api [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "run_demo.py", line 59, in query2vec_api
    outs = list(query2vec(batch_query))
  File "/data/code-server/baseline/DensePhrases/densephrases/utils/embed_utils.py", line 412, in get_question_results
    outputs = model(**inputs)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/code-server/baseline/DensePhrases/densephrases/encoder.py", line 177, in forward
    query_start, query_end = self.embed_query(input_ids_, attention_mask_, token_type_ids_)
  File "/data/code-server/baseline/DensePhrases/densephrases/encoder.py", line 132, in embed_query
    outputs_s_ = self.query_start_encoder(
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 992, in forward
    embedding_output = self.embeddings(
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 214, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/envs/densephrases-v1.1.0/lib/python3.8/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
02/14/2023 07:08:04 - ERROR - tornado.access -   500 POST /query2vec_api (127.0.0.1) 7.52ms
```

I tried to figure out input and output shape, but still don't know what to do to get them.
It would be appreciated if you could help me. Thanks in advance.

**Comment by Jenny-Jo** [comment]
Problem solved.
The main cause of the problem was wrong configuration.
When loading encoder from pretrained model in local, not only argument pretrained_name_or_path but also config_name and tokenizer_name shoule be set as a same model dir. Because in class Options , method add_model_options() makes the model spanebert as default.
